apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argo
  name: artifact-repository
  annotations:
    workflows.argoproj.io/default-artifact-repository: my-artifact-repository
data:
  my-artifact-repository: |
    s3:
      bucket: my-bucket
      endpoint: minio-service.minio:9000
      insecure: true
      accessKeySecret:
        name: minio-cred
        key: accessKey
      secretKeySecret:
        name: minio-cred
        key: secretKey