apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
      namespace: minio
    spec:
      containers:
        - name: main
          image: minio/minio:RELEASE.2022-11-17T23-20-09Z
          env:
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: dashboard
          command: [minio, server, --console-address, ":9001", /data]
          lifecycle:
            postStart:
              exec:
                command: [mkdir, -p, /data/my-bucket]
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: s3-api
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: web-api
  selector:
    app: minio
